import { createHash, randomBytes } from "node:crypto";
import type { GitHubExportConfig } from "@/lib/github/config";
import type { RunRecord } from "@/lib/repository";

function escapeMarkdown(value: string) {
  return value.replace(/[\\`*_{}\[\]()#+.!|<>-]/g, "\\$&");
}

function evidenceLink(config: GitHubExportConfig, reference: string) {
  const [runId, ...fileParts] = reference.split("/");
  const pathname = `/api/evidence/${encodeURIComponent(runId)}/${encodeURIComponent(fileParts.join("/"))}`;
  return new URL(pathname, config.publicAppUrl).toString();
}

export type GitHubIssuePreview = {
  title: string;
  body: string;
  repository: string;
  previewHash: string;
  previewToken: string;
};

export function issueMarker(idempotencyKey: string) {
  return `<!-- specsentry-export:${idempotencyKey} -->`;
}

export function buildGitHubIssuePreview(run: RunRecord, config: GitHubExportConfig): GitHubIssuePreview {
  const review = run.findingReview;
  if (run.status !== "failed" || !run.evaluation?.finding || !review || review.status !== "approved") {
    throw new Error("An approved failed finding is required before preview.");
  }
  const current = review.current;
  const runUrl = new URL(`/?run=${encodeURIComponent(run.id)}`, config.publicAppUrl).toString();
  const reproduction = current.reproductionSteps.map((step, index) => `${index + 1}. ${escapeMarkdown(step)}`).join("\n");
  const evidenceRows = review.evidenceReferences.map((reference, index) =>
    `| Captured evidence | \`${escapeMarkdown(reference)}\` | [Screenshot ${index + 1}](${evidenceLink(config, reference)}) |`,
  ).join("\n");
  const normalizedTitle = current.title.replace(/\s+/g, " ").trim();
  const title = `[SpecSentry/${current.severity.toUpperCase()}] ${normalizedTitle}`.slice(0, 256);
  const body = [
    issueMarker(review.idempotencyKey),
    "> Generated by SpecSentry from an AI-generated assessment, a human-edited and approved finding, and captured browser evidence.",
    "",
    "## Run and criterion",
    "",
    `- **Run ID:** \`${run.id}\``,
    `- **Run report:** [Open the persisted SpecSentry report](${runUrl})`,
    `- **Criterion:** ${escapeMarkdown(run.request.input.acceptanceCriteria)}`,
    `- **Human-approved severity:** **${escapeMarkdown(current.severity)}**`,
    "",
    "## Summary",
    "",
    escapeMarkdown(current.summary),
    "",
    "## Expected result",
    "",
    escapeMarkdown(current.expectedResult),
    "",
    "## Actual result",
    "",
    escapeMarkdown(current.actualResult),
    "",
    "## Reproduction steps",
    "",
    reproduction,
    "",
    "## Last successful step",
    "",
    escapeMarkdown(review.lastSuccessfulStep || "No successful step was identified."),
    "",
    "## Suggested next test",
    "",
    escapeMarkdown(current.suggestedNextTest),
    "",
    "## Evidence",
    "",
    "| Source | Reference | Absolute link |",
    "| --- | --- | --- |",
    evidenceRows,
    "",
    "## Source attribution",
    "",
    "- **AI-generated:** the immutable original evaluator finding retained in the SpecSentry run.",
    "- **Human-edited:** the current fields above, explicitly approved before export.",
    "- **Captured evidence:** the read-only browser screenshots listed above.",
    "",
    "_Generated by SpecSentry. Verify the evidence and approved wording before using this issue for engineering decisions._",
  ].join("\n");
  return {
    title,
    body,
    repository: config.repository,
    previewHash: createHash("sha256").update(`${title}\n${body}`).digest("hex"),
    previewToken: randomBytes(24).toString("hex"),
  };
}
